In [2]:
import numpy as np

In [28]:
from re import I
def l_k(data_x , k,x):
  l_k = 1
  for i in range(len(data_x)):
    if (i!=k) and (i%2!=0) :
      l_k*=((x-data_x[i])/(data_x[k]-data_x[i]))
  return l_k

def get_poly_lagrange(data_x,data_y,x_arr):
  output = []
  for j in range(len(x_arr)):
    sum = 0
    for k in range(len(data_x)):
      if (k%2==0):
        sum+=data_y[k]*l_k(data_x,k,x_arr[j])
    output.append(sum)
  return output
x_arr = np.linspace(5,11,35)
da_x = [0,3,4,7,13]
da_y = [5,8,11,19,26]
print(get_poly_lagrange(da_x,da_y,x_arr))

[11.980952380952381, 11.887675070028012, 11.607843137254905, 11.141456582633053, 10.488515406162465, 9.649019607843137, 8.622969187675071, 7.410364145658262, 6.0112044817927135, 4.425490196078434, 2.6532212885154065, 0.6943977591036391, -1.4509803921568576, -3.782913165266117, -6.301400560224091, -9.006442577030818, -11.898039215686282, -14.976190476190476, -18.240896358543402, -21.692156862745108, -25.32997198879552, -29.154341736694697, -33.16526610644258, -37.36274509803921, -41.74677871148457, -46.31736694677872, -51.074509803921615, -56.0182072829132, -61.14845938375351, -66.46526610644256, -71.96862745098042, -77.65854341736696, -83.53501400560226, -89.5980392156863, -95.84761904761905]


In [66]:
def modified_vandermonde(data_x,data_y,x):
  n = len(data_x)
  modified = np.zeros([n,n])
  for i in range(0,n,1):
    for j in range(0,n//2,1):
      if i%2!=0:
        modified[i][j] = data_x[i]**j
  for i in range(n,1):
    for j in range(n//2,n,1):
      if i%2==0:
        modified[i][j] = data_x[i]**j
  print(modified)

data_x = np.array([1,3,6,8,9,11])
data_y = np.array([4,10,19,25,28,34])
x = 2
modified_vandermonde(data_x,data_y,x)

[[  0.   0.   0.   0.   0.   0.]
 [  1.   3.   9.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  1.   8.  64.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  1.  11. 121.   0.   0.   0.]]
